[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
friend_bet_contracts = "FB867jaqgavE577W5uZ9jTMcLqD1nLMqFHYdrJKYmcEj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/sushmitmacair/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
